sudo: required
services:
    - docker

before_install:
    - docker image build -t deevibe/docker-react -f Dockerfile.dev .

script:
    - docker container run deevibe/docker-react npm run test -- --coverage
